<?php

class Loup extends Animal // extends = héritage
{
    public function __construct($nom, $sexe)
    {
        parent::__construct($nom, 'Loup', 'Lupus', $sexe);
    }

    public function cri()
    {
        echo $this->getNom().' hurle quand il y a la pleine lune<br>';
        $this->seDeplacer();
    }

    public function seDeplacer()
    {
        parent::seDeplacer(); // TODO: Change the autogenerated stub
    }

    public function nage()
    {
        echo $this->getNom().' nage mais ce noie<br>';
    }
}
